### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by br1egel** [ihmcrobotics/ihmc-optimizer-wrappers#2]
Hi,
in your QpOASESSwigWrapper.java seems to be missing some sources :
us.ihmc.convexOptimization.qpOASES.SQProblem;
us.ihmc.convexOptimization.qpOASES.returnValue;

Do you mind to submit it ? 

Kind Regards

**Comment by dljsjr** [comment]
Hi @br1egel,

The files you're referencing are files that are generated by Swig. They are not in the version control repository because we adhere to the (fairly common) convention of not version controlling generated files.

If you are using our software from .jars as distributed on Bintray, you will find that the generated source files you are looking for are in the "sources" jar. If you are working with this software from source and trying to build it yourself, you will need to install SWIG and CMake then run the C++ part of the build to generate the files you're looking for before running the Java part of the build.

Hope that helps!

**Comment by br1egel** [comment]
thanks for fast reply, just found your bintray, which I didn't know before.
Saved me plenty of time when integrating my model predictive controller.
Very good work!
Regards
